generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\ElementTagsProposition
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: List for elements tags propositions
      display: [ id, element, user, tags ]
      actions:
        new: ~
      object_actions:
        show: ~
        edit: ~
        delete: ~
  filters:
    params:
      display: [ element, user ]
  new:
    params:
      title: New object for AdminBundle
      display: [ element, user, tags ]
      actions:
        list: ~
  edit:
    params:
      title: "You're editing tags propotions for \"%object%\"|{ %object%: ElementTagsProposition.element.name }|"
      display: [ element, user, tags ]
      actions:
        list: ~
  show:
    params:
      title: "You're editing tags propotions \"%object%\"|{ %object%: ElementTagsProposition.element.name }|"
      display: [ element, user, tags ]
      actions:
        list: ~
        new: ~
  delete: ~
