generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\FollowGroup
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    follower:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users
    group:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: groups

builders:
  list:
    params:
      title: List for Follow Groups
      display: [ follower, group ]
      actions:
        new: ~
      object_actions:
        show: ~
        edit: ~
        delete: ~
  filters:
    params:
      display: [ follower, group ]
  new:
    params:
      title: New object for Group Follow
      display: [ follower, group ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: FollowGroup.group.name }|"
      display: [ follower, group ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: FollowGroup.group.name }|"
      display: [ follower, group ]
      actions:
        list: ~
        new: ~
  delete: ~
