generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\UsersTagsFavorites
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    user:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users
    tag:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: tags

builders:
  list:
    params:
      title: List for User Tags Favorites
      display: [ user, tag ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ user, tag ]
  new:
    params:
      title: New User tag favorite
      display: [ user, tag ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing an tag favorite \"%object%\"|{ %object%: UsersTagsFavorites.user.username }|"
      display: [ user, tag ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: UsersTagsFavorites.user.username }|"
      display: [ user, tag ]
      actions:
        list: ~
        new: ~
  delete: ~
