generator: admingenerator.generator.doctrine

params:
  model: Muzich\CoreBundle\Entity\Element
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    owner:
      label: Owner name
      sort_on: owner.name
      getter: owner.name
      addFormOptions:
        property: name

builders:
  list:
    params:
      title: List for Element
      display: [ id, name, owner, type ]
      actions:
        new: ~
      object_actions:
        show: ~
        regenerate:
          route: Muzich_AdminBundle_Admin_element_regenerate
        edit: ~
        delete: ~
  filters:
    params:
      fields: ~
      display: [ type, name, url, owner, created, updated, need_tags ]
  new:
    params:
      title: New Element
      display:
        "Media" : [name, type, url]
        "Relations" : [owner, group]
        "System" : [need_tags]
      actions:
        list: ~
  edit:
    params:
      title: "You're editing element \"%object%\"|{ %object%: Element.name }|"
      display:
        "Media" : [name, type, url]
        "Relations" : [owner, group]
        "System" : [need_tags]
      actions:
        list: ~
  show:
    params:
      title: "You're viewing element \"%object%\"|{ %object%: Element.name }|"
      display:
        "Media" : [name, type, url, embed]
        "Relations" : [owner, group]
        "System" : [need_tags]
        "Moderation" : [count_report, count_comment_report]
      actions:
        list: ~
        new: ~
  delete: ~
