generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\Group
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    owner:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users

builders:
  list:
    params:
      title: List for Groups
      display: [name, owner, open]
      actions:
        new: ~
      object_actions:
        show: ~
        edit: ~
        delete: ~
  filters:
    params:
      display: [owner, name, open]
  new:
    params:
      title: New Group
      display: [name, owner, description, open]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: Group.name }|"
      display: [name, owner, description, open]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: Group.name }|"
      display: [name, owner, description, open]
      actions:
        list: ~
        new: ~
  delete: ~
