generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\FollowUser
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    follower:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users
    followed:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users

builders:
  list:
    params:
      title: List for User Follows
      display: [ follower, followed ]
      actions:
        new: ~
      object_actions:
        show: ~
        edit: ~
        delete: ~
  filters:
    params:
      display: [ follower, followed ]
  new:
    params:
      title: New object for User Follow
      display: [ follower, followed ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing following for the object \"%object%\"|{ %object%: FollowUser.followed.username }|"
      display: [ follower, followed ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing following for the object \"%object%\"|{ %object%: FollowUser.followed.username }|"
      display: [ follower, followed ]
      actions:
        list: ~
        new: ~
  delete: ~
