generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\GroupsTagsFavorites
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    group:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: groups
    tag:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: tags

builders:
  list:
    params:
      title: List for Group Tags Favorites
      display: [ group, tag ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ group, tag ]
  new:
    params:
      title: New Group tag favorite
      display: [ group, tag ]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: GroupsTagsFavorites.group.name }|"
      display: [ group, tag ]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: GroupsTagsFavorites.group.name }|"
      display: [ group, tag ]
      actions:
        list: ~
        new: ~
  delete: ~
