generator: admingenerator.generator.doctrine
params:
  model: Muzich\CoreBundle\Entity\EventArchive
  namespace_prefix: Muzich
  bundle_name: AdminBundle
  fields:
    user:
      formType: shtumi_ajax_autocomplete
      formOptions:
        entity_alias: users

builders:
  list:
    params:
      title: List for Event archives
      display: [id, type, user, count]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ type, user ]
  new:
    params:
      title: New Event archive
      display: [ type, user, count]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing event archive for \"%object%\"|{ %object%: EventArchive.user.username }|"
      display: [ type, user, count]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're editing event archive for \"%object%\"|{ %object%: EventArchive.user.username }|"
      display: [ type, user, count]
      actions:
        list: ~
        new: ~
  delete: ~
