Muzich_AdminBundle_Admin_element_regenerate:
  pattern:  /Admin_element/{pk}/regenerate
  defaults: { _controller:Muzich\AdminBundle\Controller\Admin_element\EditController::regenerateAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_element_accept:
  pattern:  /Moderate_element/{pk}/accept
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_element\EditController::acceptAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_element_refuse:
  pattern:  /Moderate_element/{pk}/refuse
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_element\EditController::refuseAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_tag_accept:
  pattern:  /Moderate_tag/{pk}/accept
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_tag\EditController::acceptAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_tag_refuse:
  pattern:  /Moderate_tag/{pk}/refuse
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_tag\EditController::refuseAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_comment_list:
  pattern:  /Moderate_comment/
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_comment\ListController::listAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_comment_accept:
  pattern:  /Moderate_comment/{element_id}/{date}/accept
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_comment\EditController::acceptAction }
  requirements:
    _method:  GET
    
Muzich_AdminBundle_Moderate_comment_refuse:
  pattern:  /Moderate_comment/{element_id}/{date}/refuse
  defaults: { _controller:Muzich\AdminBundle\Controller\Moderate_comment\EditController::refuseAction }
  requirements:
    _method:  GET

