MuzichAdminBundle_moderate_index:
  pattern:  /admin/moderate
  defaults: { _controller: MuzichAdminBundle:Moderate:index }

##

MuzichAdminBundle_moderate_tags:
  pattern:  /admin/moderate/tags
  defaults: { _controller: MuzichAdminBundle:Moderate:tags }
  
MuzichAdminBundle_moderate_tags_accept_tag:
  pattern:  /admin/moderate/tags/{tag_id}/accept
  defaults: { _controller: MuzichAdminBundle:Moderate:tagAccept }
  
MuzichAdminBundle_moderate_tags_refuse_tag:
  pattern:  /admin/moderate/tags/{tag_id}/refuse
  defaults: { _controller: MuzichAdminBundle:Moderate:tagRefuse }
  
MuzichAdminBundle_moderate_tags_replace_tag:
  pattern:  /admin/moderate/tags/{tag_id}/replace/{tag_new_id}
  defaults: { _controller: MuzichAdminBundle:Moderate:tagReplace, tag_new_id: null }
  
##

moderate_elements_index:
  pattern:  /admin/moderate/elements
  defaults: { _controller: MuzichAdminBundle:Moderate:elements }
  
moderate_element_delete:
  pattern:  /admin/moderate/element/delete/{element_id}
  defaults: { _controller: MuzichAdminBundle:Moderate:deleteElement }
  
moderate_element_clean:
  pattern:  /admin/moderate/element/clean/{element_id}
  defaults: { _controller: MuzichAdminBundle:Moderate:cleanElement }
  
##

moderate_comments_index:
  pattern:  /admin/moderate/comments
  defaults: { _controller: MuzichAdminBundle:Moderate:comments }

moderate_comment_clean:
  pattern:  /admin/moderate/comment/{element_id}/{date}/clean
  defaults: { _controller: MuzichAdminBundle:Moderate:commentClean }

moderate_comment_refuse:
  pattern:  /admin/moderate/comment/{element_id}/{date}/refuse
  defaults: { _controller: MuzichAdminBundle:Moderate:commentRefuse }