parameters:
#    muzich_admin.example.class: Muzich\AdminBundle\Example

services:
#    muzich_admin.example:
#        class: %muzich_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
