
mynetwork_index:
  pattern:  /my-network
  defaults: { _controller: MuzichMynetworkBundle:Mynetwork:index }
  
mynetwork_search:
  pattern:  /my-network/search
  defaults: { _controller: MuzichMynetworkBundle:Mynetwork:search }
  
#mynetwork_search:
#  pattern:  /my-network/search/do
#  defaults: { _controller: MuzichMynetworkBundle:Mynetwork:search }
  