## Routing du Bundle Index

index_without_locale:
    pattern:  /hello/
    defaults: { _controller: MuzichCoreBundle:Core:automaticLanguage }
    
index:
    pattern:  /hello/{_locale}
    defaults: { _controller: MuzichIndexBundle:Index:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile/
    defaults: { _locale: fr }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register/
    defaults: { _locale: fr }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults: { _locale: fr }

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/change-password/
    defaults: { _locale: fr }
