
favorite_add:
  pattern:   /favorite/add/{id}/{token}
  defaults: { _controller: MuzichFavoriteBundle:Favorite:add }
  
favorite_remove:
  pattern:   /favorite/remove/{id}/{token}
  defaults: { _controller: MuzichFavoriteBundle:Favorite:remove }

favorites_my_list:
  pattern:   /favorites
  defaults: { _controller: MuzichFavoriteBundle:Favorite:myList }

favorite_user_list:
  pattern:   /user/{slug}/favorites
  defaults: { _controller: MuzichFavoriteBundle:Favorite:userList }