
favorite_add:
  pattern:   /favorite/add/{id}/{token}
  defaults: { _controller: MuzichFavoriteBundle:Favorite:add }
  
favorite_remove:
  pattern:   /favorite/remove/{id}/{token}
  defaults: { _controller: MuzichFavoriteBundle:Favorite:remove }

favorites_my_list:
  pattern:   /favorites
  defaults: { _controller: MuzichFavoriteBundle:Favorite:myList, topmenu: myfavorites }

favorite_user_list:
  pattern:   /user/{slug}/favorites
  defaults: { _controller: MuzichFavoriteBundle:Favorite:userList }

favorite_get:
  pattern:   /favoritesajax/{user_id}/getElements/{tags_ids_json}/{id_limit}/{invert}
  defaults: { _controller: MuzichFavoriteBundle:Favorite:getElements, tags_ids_json: null, id_limit: null, invert: false }