parameters:
#    muzich_favorite.example.class: Muzich\FavoriteBundle\Example

services:
#    muzich_favorite.example:
#        class: %muzich_favorite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
