imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        # UPGRADE 2.1
        storage_id: session.storage.mock_file 

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   muzich_test
        user:     %database_user%
        password: %database_password%
        charset:  utf8

parameters:
    env: test
