imports:
    - { resource: config.yml }

#doctrine:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: error@siga-jsp.fr
            to_email:   sevajol.bastien@gmail.com
            subject:    An Error Occurred!
            level:      debug

parameters:
    env: prod
    siteurl:      http://muzi.ch
    siteurl_www:  http://www.muzi.ch