imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        # UPGRADE 2.1
        storage_id: session.storage.mock_file 

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

parameters:
    env: test