MuzichMynetworkBundle:
    resource: "@MuzichMynetworkBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

MuzichCoreBundle:
  resource: "@MuzichCoreBundle/Resources/config/routing.yml"
  prefix: /
  
MuzichIndexBundle:
  resource: "@MuzichIndexBundle/Resources/config/routing.yml"
  prefix: /

MuzichHomeBundle:
  resource: "@MuzichHomeBundle/Resources/config/routing.yml"
  prefix: /

MuzichUserBundle:
  resource: "@MuzichUserBundle/Resources/config/routing.yml"
  prefix: /
