# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
  
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
  
MuzichAdminBundle:
  resource: "@MuzichAdminBundle/Resources/config/routing.yml"
  
MuzichIndexBundle:
  resource: "@MuzichIndexBundle/Resources/config/routing.yml"
  prefix: /
    
change_language:
  pattern:  /change-language/{language}/{redirect}
  defaults: { _controller: MuzichCoreBundle:Core:changeLanguage, redirect: referer }
  
language_automatic:
  pattern:  /auto-language
  defaults: { _controller: MuzichCoreBundle:Core:automaticLanguage }
  
share_form:
  pattern:  /share-from/
  defaults: { _controller: MuzichCoreBundle:Core:shareFrom }
  
MuzichCoreBundle:
  resource: "@MuzichCoreBundle/Resources/config/routing.yml"
  prefix: /{_locale}/

  
MuzichHomeBundle:
  resource: "@MuzichHomeBundle/Resources/config/routing.yml"
  prefix: /{_locale}/
    
# On doit rajouter une route au cas ou la langue n'est pas précisé.
home_bis:
  pattern:  /
  defaults: { _controller: MuzichHomeBundle:Home:index }
  
MuzichUserBundle:
  resource: "@MuzichUserBundle/Resources/config/routing.yml"
  prefix: /{_locale}/

MuzichMynetworkBundle:
  resource: "@MuzichMynetworkBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/
  
MuzichGroupBundle:
  resource: "@MuzichGroupBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/
  
MuzichFavoriteBundle:
  resource: "@MuzichFavoriteBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/
  
MuzichCommentBundle:
  resource: "@MuzichCommentBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/
  