

my_account:
  pattern:  /account
  defaults: { _controller: MuzichUserBundle:User:account }
     
change_password:
  pattern: /account/change-password
  defaults: { _controller: MuzichUserBundle:User:changePassword }
  
register:
  pattern: /register/do
  defaults: { _controller: MuzichUserBundle:User:register }
  
start:
  pattern: /start
  defaults: { _controller: MuzichUserBundle:User:start }
  
update_tag_favorites:
  pattern: /account/update-tag-favorites/{redirect}
  defaults: { _controller: MuzichUserBundle:User:updateTagFavorites, redirect: home }
    
change_email_request:
  pattern: /account/change-email/request
  defaults: { _controller: MuzichUserBundle:User:changeEmailRequest }
  requirements:
    _method:  POST
    
change_email_confirm:
  pattern: /account/change-email/confirm/{token}
  defaults: { _controller: MuzichUserBundle:User:changeEmailConfirm }