my_account:
  pattern:  /account
  defaults: { _controller: MuzichUserBundle:User:account }
     
change_password:
  pattern: /account/change-password
  defaults: { _controller: MuzichUserBundle:User:changePassword }
  
register:
  pattern: /register/do
  defaults: { _controller: MuzichUserBundle:User:register }
  
start:
  pattern: /start
  defaults: { _controller: MuzichUserBundle:User:start }
  
update_tag_favorites:
  pattern: /account/update-tag-favorites/{redirect}
  defaults: { _controller: MuzichUserBundle:User:updateTagFavorites, redirect: home }
    
change_email_request:
  pattern: /account/change-email/request
  defaults: { _controller: MuzichUserBundle:User:changeEmailRequest }
  requirements:
    _method:  POST
    
change_email_confirm:
  pattern: /account/change-email/confirm/{token}
  defaults: { _controller: MuzichUserBundle:User:changeEmailConfirm }

email_confirm:
  pattern: /account/email/confirm/{token}
  defaults: { _controller: MuzichUserBundle:User:confirmEmail }

send_email_confirm:
  pattern: /account/email/send-confirm
  defaults: { _controller: MuzichUserBundle:User:sendEmailConfirm }

update_address:
  pattern: /ajax/update-address/{token}
  defaults: { _controller: MuzichUserBundle:User:updateAddress }
  
event_view_elements:
  pattern: /event/view/elements/{event_id}
  defaults: { _controller: MuzichUserBundle:Event:viewElements }

event_delete:
  pattern: /event/delete/{event_id}/{token}
  defaults: { _controller: MuzichUserBundle:Event:delete }
  requirements:
    _method:  GET
    message_id: \d+
  
user_update_avatar:
  pattern:  /account/update-avatar
  defaults: { _controller: MuzichUserBundle:User:updateAvatar }
  requirements:
    _method:  POST

user_update_preferences:
  pattern:  /account/update-preferences
  defaults: { _controller: MuzichUserBundle:User:updatePreferences }
  requirements:
    _method:  POST
  
user_hide_help:
  pattern: /account/update-help/hide/{help_id}/{token}
  defaults: { _controller: MuzichUserBundle:User:updateHelpViewed }
  requirements:
    _method:  POST

subscribe_or_login:
  pattern: /ajax/subscribe-or-login
  defaults: { _controller: MuzichUserBundle:User:subscribeOrLogin }

change_username:
  pattern: /account/username/update
  defaults: { _controller: MuzichUserBundle:User:changeUsername }
