

my_account:
  pattern:  /account
  defaults: { _controller: MuzichUserBundle:User:account }
     
change_password:
  pattern: /account/change-password
  defaults: { _controller: MuzichUserBundle:User:changePassword }
  
register:
  pattern: /register/do
  defaults: { _controller: MuzichUserBundle:User:register }
  
start:
  pattern: /start
  defaults: { _controller: MuzichUserBundle:User:start }
  