## Routing du Bundle

home:
  pattern:  /{_locale}
  defaults: { _controller: MuzichHomeBundle:Home:index, _locale: fr }
  
show_user:
  pattern: /{_locale}/user/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showUser, _locale: fr }
  
show_group:
  pattern: /{_locale}/group/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showGroup, _locale: fr }
