## Routing du Bundle

home:
  pattern:  /
  defaults: { _controller: MuzichHomeBundle:Home:index, network: network_public, login: false }
  
home_login:
  pattern:  /login
  defaults: { _controller: MuzichHomeBundle:Home:index, network: network_public, login: true }
  
home_more:
  pattern:  /more/{count}
  defaults: { _controller: MuzichHomeBundle:Home:index, count: null, login: false }
  
show_user:
  pattern: /user/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showUser, topmenu: showuser }
  
show_user_more:
  pattern: /user/{slug}/more/{count}
  defaults: { _controller: MuzichHomeBundle:Show:showUser, count: null, topmenu: showgroup }
  
show_group:
  pattern: /group/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showGroup }
  
show_group_more:
  pattern: /group/{slug}/more/{count}
  defaults: { _controller: MuzichHomeBundle:Show:showGroup, count: null }

show_elements_get:
  pattern:   /show/{type}/{object_id}/getElements/{tags_ids_json}/{id_limit}/{invert}
  defaults: { _controller: MuzichHomeBundle:Show:getElements, id_limit: null, invert: false }

  