## Routing du Bundle

home:
  pattern:  /
  defaults: { _controller: MuzichHomeBundle:Home:index }
  
home_more:
  pattern:  /more/{count}
  defaults: { _controller: MuzichHomeBundle:Home:index, count: null }
  
show_user:
  pattern: /user/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showUser }
  
show_group:
  pattern: /group/{slug}
  defaults: { _controller: MuzichHomeBundle:Show:showGroup }
