

search_elements:
  pattern:  /search-elements
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
   
follow:
  pattern:  /follow/{type}/{id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:follow }
   
element_add:
  pattern:  /element/add/{group_slug}
  defaults: { _controller: MuzichCoreBundle:Core:elementAdd, group_slug: null }

search_tag:
  pattern: /search/tag/{string_search}
  defaults: { _controller: MuzichCoreBundle:Search:searchTag, string_search: null }
  
search_tag_ig_by_name:
  pattern: /search/tagid/{string_search}
  defaults: { _controller: MuzichCoreBundle:Search:searchTagId, string_search: null }

filter_clear:
  pattern: /filter/clear
  defaults: { _controller: MuzichCoreBundle:Core:filterClear }

filter_mytags:
  pattern: /filter/my-tags
  defaults: { _controller: MuzichCoreBundle:Core:filterMytags }

####

info_about:
  pattern: /info/about
  defaults: { _controller: MuzichCoreBundle:Info:about }
  
info_development:
  pattern: /info/development
  defaults: { _controller: MuzichCoreBundle:Info:development }