

search_elements:
  pattern:  /search-elements
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
  
search_elements_more:
  pattern:  /search-elements/{id_limit}/{invertcolors}
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
   
search_elements_show_more_empty:
  pattern:  /search-elements/show/{type}/{object_id}
  defaults: { _controller: MuzichCoreBundle:Search:searchElementsShow }
    
search_elements_show_more:
  pattern:  /search-elements/show/{type}/{object_id}/{id_limit}/{invertcolors}
  defaults: { _controller: MuzichCoreBundle:Search:searchElementsShow }
   
follow:
  pattern:  /follow/{type}/{id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:follow }
   
element_add:
  pattern:  /element/add/{group_slug}
  defaults: { _controller: MuzichCoreBundle:Core:elementAdd, group_slug: null }

search_tag:
  pattern: /search/tag/{string_search}/{timestamp}
  defaults: { _controller: MuzichCoreBundle:Search:searchTag, string_search: null, timestamp: null }
  
search_tag_ig_by_name:
  pattern: /search/tagid/{string_search}
  defaults: { _controller: MuzichCoreBundle:Search:searchTagId, string_search: null }

filter_clear:
  pattern: /filter/clear
  defaults: { _controller: MuzichCoreBundle:Core:filterClear }

filter_mytags:
  pattern: /filter/my-tags
  defaults: { _controller: MuzichCoreBundle:Core:filterMytags }

ajax_get_favorites_tags:
  pattern: /ajax/my-favorites-tags
  defaults: { _controller: MuzichCoreBundle:Core:getFavoriteTags }

ajax_add_tag:
  pattern: /ajax/add-tag/{name}
  defaults: { _controller: MuzichCoreBundle:Core:addTag, name: null }
  

####

info_about:
  pattern: /info/about
  defaults: { _controller: MuzichCoreBundle:Info:about }
  
info_development:
  pattern: /info/development
  defaults: { _controller: MuzichCoreBundle:Info:development }

info_sites:
  pattern: /info/sites
  defaults: { _controller: MuzichCoreBundle:Info:sites }
  
####

element_edit:
  pattern: /element/{element_id}/edit
  defaults: { _controller: MuzichCoreBundle:Element:edit }

element_update:
  pattern: /element/{element_id}/update
  defaults: { _controller: MuzichCoreBundle:Element:update }
  
element_remove:
  pattern: /element/{element_id}/remove
  defaults: { _controller: MuzichCoreBundle:Element:remove }
  
  