

search_elements:
  pattern:  /search-elements
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
   
follow:
  pattern:  /follow/{type}/{id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:follow }
   
element_add:
  pattern:  /element/add/{group_slug}
  defaults: { _controller: MuzichCoreBundle:Core:elementAdd, group_slug: null }
