

search_elements:
  pattern:  /search-elements
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
  
search_elements_more:
  pattern:  /search-elements/{id_limit}/{invertcolors}
  defaults: { _controller: MuzichCoreBundle:Search:searchElements }
   
search_elements_show_more_empty:
  pattern:  /search-elements/show/{type}/{object_id}
  defaults: { _controller: MuzichCoreBundle:Search:searchElementsShow }
    
search_elements_show_more:
  pattern:  /search-elements/show/{type}/{object_id}/{id_limit}/{invertcolors}
  defaults: { _controller: MuzichCoreBundle:Search:searchElementsShow }
   
global_search_elements_empty:
  pattern:  /global-search-elements/
  defaults: { _controller: MuzichCoreBundle:Search:globalSearchMore }
  
global_search_elements:
  pattern:  /global-search-elements/{last_id}/{string}
  defaults: { _controller: MuzichCoreBundle:Search:globalSearchMore }
   
follow:
  pattern:  /follow/{type}/{id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:follow }
   
element_add:
  pattern:  /element/add/{group_slug}
  defaults: { _controller: MuzichCoreBundle:Core:elementAdd, group_slug: null }

search_tag:
  pattern: /search/tag/{timestamp}
  defaults: { _controller: MuzichCoreBundle:Search:searchTag, timestamp: null }
  
search_tag_ig_by_name:
  pattern: /search/tagid/{string_search}
  defaults: { _controller: MuzichCoreBundle:Search:searchTagId, string_search: null }

filter_clear:
  pattern: /filter/clear
  defaults: { _controller: MuzichCoreBundle:Core:filterClear }

filter_mytags:
  pattern: /filter/my-tags
  defaults: { _controller: MuzichCoreBundle:Core:filterMytags }

ajax_get_favorites_tags:
  pattern: /ajax/my-favorites-tags
  defaults: { _controller: MuzichCoreBundle:Core:getFavoriteTags }

ajax_add_tag:
  pattern: /ajax/add-tag
  defaults: { _controller: MuzichCoreBundle:Core:addTag }
  
ajax_element_add_vote_good:
  pattern: /ajax/element/vote/add/good/{element_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Element:addVoteGood }
  
ajax_element_remove_vote_good:
  pattern: /ajax/element/vote/remove/good/{element_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Element:removeVoteGood }

ajax_filter_remove_ids:
  pattern: /ajax/filter/remove/ids
  defaults: { _controller: MuzichCoreBundle:Core:filterRemoveIds }

####

info_about:
  pattern: /info/about
  defaults: { _controller: MuzichCoreBundle:Info:about }
  
info_development:
  pattern: /info/development
  defaults: { _controller: MuzichCoreBundle:Info:development }

info_sites:
  pattern: /info/sites
  defaults: { _controller: MuzichCoreBundle:Info:sites }
  
####

element_edit:
  pattern: /element/{element_id}/edit
  defaults: { _controller: MuzichCoreBundle:Element:edit }

element_update:
  pattern: /element/{element_id}/update/{dom_id}
  defaults: { _controller: MuzichCoreBundle:Element:update }
  
element_remove:
  pattern: /element/{element_id}/remove
  defaults: { _controller: MuzichCoreBundle:Element:remove }
  
element_new_count:
  pattern: /ajax/element/new/count/{refid}
  defaults: { _controller: MuzichCoreBundle:Element:countNews, refid: null }
  
element_new_get:
  pattern: /ajax/element/new/get/{refid}
  defaults: { _controller: MuzichCoreBundle:Element:getNews, refid: null }
  
##

ajax_tag_add_to_favorites:
  pattern: /ajax/tag/add-to-favorites/{tag_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:addTagToFavorites }

ajax_set_element_group:
  pattern: /ajax/element/set-group/{element_id}/{group_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:setElementGroup }
  
ajax_report_element:
  pattern: /ajax/element/report/{element_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Core:reportElement }
  
ajax_reshare_element:
  pattern: /ajax/element/reshare/{element_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Element:reshare }
  
ajax_element_propose_tags_open:
  pattern: /ajax/element/propose/tags/{element_id}
  defaults: { _controller: MuzichCoreBundle:Element:proposeTagsOpen }
  
ajax_element_propose_tags_proceed:
  pattern: /ajax/element/propose/tags/{element_id}/proceed/{token}
  defaults: { _controller: MuzichCoreBundle:Element:proposeTagsProceed }
  
ajax_element_proposed_tags_view:
  pattern: /ajax/element/proposed/tags/{element_id}/view
  defaults: { _controller: MuzichCoreBundle:Element:proposedTagsView }
  
ajax_element_proposed_tags_accept:
  pattern: /ajax/element/proposed/tags/accept/{proposition_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Element:proposedTagsAccept }
  
ajax_element_proposed_tags_refuse:
  pattern: /ajax/element/proposed/tags/refuses/{element_id}/{token}
  defaults: { _controller: MuzichCoreBundle:Element:proposedTagsRefuse }
  
## search
  
global_search:
  pattern:  /search
  defaults: { _controller: MuzichCoreBundle:Search:global }
  
  
## lol

teapot:
  pattern: /what/are/you
  defaults: { _controller: MuzichCoreBundle:Info:teapot }
  
#

element_retrieve_api_datas:
  pattern: /ajax/element/get/datas/api
  defaults: { _controller: MuzichCoreBundle:Element:getDatasApi }
  requirements:
    method:  POST