
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                default_target_path: /
            logout:
                path:   /logout
                target: /
            anonymous:  true
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    ## La en tant qu'exemple, exploiter ça (http://j-place.developpez.com/tutoriels/php/ameliorez-vos-applications-developpees-avec-symfony2/#LVI-A-3)
#    access_control:
#        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
#        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        
#        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
#        - { path: ^/myapp/admin/, role: ROLE_ADMIN }
#        
#        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
#        - { path: ^/myapp/change-password, role: ROLE_USER }
#
#        # PAGES ACCESSIBLES À TOUS
#        - { path: ^/myapp.*, role: IS_AUTHENTICATED_ANONYMOUSLY }