playlists_user:
  pattern: /user/{user_slug}/playlists
  defaults: { _controller: MuzichPlaylistBundle:Show:user, topmenu: playlists }

playlist:
  pattern: /user/{user_slug}/playlist/{playlist_id}
  defaults: { _controller: MuzichPlaylistBundle:Show:show }

playlist_delete:
  pattern: /playlist/delete/{playlist_id}/{token}
  defaults: { _controller: MuzichPlaylistBundle:Edit:delete }

playlist_unpick:
  pattern: /playlist/unpick/{playlist_id}/{token}/{redirect_owner}
  defaults: { _controller: MuzichPlaylistBundle:Edit:unpick, redirect_owner: false }

playlist_pick:
  pattern: /playlist/pick/{playlist_id}/{token}/{redirect_owner}
  defaults: { _controller: MuzichPlaylistBundle:Edit:pick, redirect_owner: false }

playlist_datas_for_autoplay:
  pattern: /ajax/autoplay/playlist/datas/{playlist_id}/{offset}
  defaults: { _controller: MuzichPlaylistBundle:Show:getAutoplayData, offset: null }

playlist_update_order:
  pattern: /ajax/playlist/order/update/{playlist_id}/{token}
  defaults: { _controller: MuzichPlaylistBundle:Edit:updateOrder }

playlist_remove_element:
  pattern: /ajax/playlist/element/remove/{playlist_id}/{index}/{token}
  defaults: { _controller: MuzichPlaylistBundle:Edit:removeElement }

playlists_add_element_prompt:
  pattern: /ajax/playlist/element/add/prompt/{element_id}
  defaults: { _controller: MuzichPlaylistBundle:Show:getAddElementPrompt }

playlists_add_element:
  pattern: /ajax/playlist/element/add/{playlist_id}/{element_id}/{token}
  defaults: { _controller: MuzichPlaylistBundle:Edit:addElement }
  
playlists_add_element_and_copy:
  pattern: /ajax/playlist/element/add-and-copy/{playlist_id}/{element_id}/{token}
  defaults: { _controller: MuzichPlaylistBundle:Edit:addElementAndCopy }

playlist_add_element_and_create:
  pattern: /ajax/playlist/element/add-and-create/{element_id}
  defaults: { _controller: MuzichPlaylistBundle:Edit:addElementAndCreate }
  