
groups_own_list:
  pattern:  /my-groups
  defaults: { _controller: MuzichGroupBundle:Default:myList }

group_add:
  pattern:   /my-groups/add
  defaults: { _controller: MuzichGroupBundle:Default:add }
    
group_edit:
  pattern:   /group/{slug}/edit
  defaults: { _controller: MuzichGroupBundle:Default:edit }
    
group_update:
  pattern:   /group/{slug}/update
  defaults: { _controller: MuzichGroupBundle:Default:update }

group_delete:
  pattern:   /group/{group_id}/delete/{token}
  defaults: { _controller: MuzichGroupBundle:Default:delete }